# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.4
addons:
 apt:
   update: true
   packages:
   - openmpi-bin
   - libopenmpi-dev
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Gridap",rev="GridapDistributed"))'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.4
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(name="Gridap",rev="GridapDistributed"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
