# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist: bionic
julia:
  - 1.4
addons:
 apt:
   update: true
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - lsb_release -a       
  - export JULIA_MPI_BINARY=""
  - export JULIA_PETSC_RealDouble_BINARY=""
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  fast_finish: true
  include:
    - stage: "MPIPETScTests"
      julia: 1.4
      os: linux
      script:
        - echo $PWD
        - julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
        - cd test/MPIPETScTests/compile
        - ./compile.sh
        - cd ../../..   
        - julia --project=. --color=yes --check-bounds=yes test/MPIPETScTests/runtests.jl -i test/MPIPETScTests/compile/GridapDistributed.so
      after_success: skip
    - stage: Documentation
      julia: 1.4
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/gridap/Gridap.jl", rev="master"));
          Pkg.add(PackageSpec(url="https://github.com/gridap/GridapDistributedPETScWrappers.jl", rev="master"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.test("GridapDistributed");
          include("docs/make.jl");'
      after_success: skip
