# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
dist: bionic
julia:
  - 1.4
addons:
 apt:
   update: true
   packages:
   - openmpi-bin
   - libopenmpi-dev
   - petsc-dev
notifications:
  email:
    on_success: never
    on_failure: always
before_script:
  - lsb_release -a       
  - export JULIA_MPI_BINARY="system"
  - export JULIA_PETSC_RealDouble_DIR="/usr/lib/petsc/"
  - export JULIA_PETSC_RealDouble_ARCH=""
  - export JULIA_PETSC_RealDouble_LIBNAME="libpetsc_real"
  - export JULIA_PETSC_RealSingle_NOBUILD="1"
  - export JULIA_PETSC_ComplexDouble_NOBUILD="1"
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.4
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/gridap/Gridap.jl", rev="master"));
          Pkg.add(PackageSpec(url="https://github.com/gridap/PETSc.jl", rev="uptodate1.4"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.test("GridapDistributed");
          include("docs/make.jl");'
      after_success: skip
