name: CI
on:
  - push 
jobs:
  SequentialCommTests:
    name: SequentialCommTests ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.4
        os:
          - ubuntu-latest
        arch:
          - x64
          - x86   
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }} 
          arch: ${{ matrix.arch }} 
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
  MPIPETScCommTests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.4
          arch: x64 
      - uses: julia-actions/julia-buildpkg@latest
      - run: echo $PWD  
      - run: julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
      - run: cd test/MPIPETScTests/compile; ./compile.sh
      - run: julia --project=. --color=yes --check-bounds=yes test/MPIPETScTests/runtests.jl -i test/MPIPETScTests/compile/GridapDistributed.so  
