name: CI
on:
  - push 
jobs:
  test:
    name: Julia
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.4
          arch: x64 
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
