name: CI
on:
  - push 
jobs:
  SequentialCommTests:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6
          arch: x64 
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
  MPIPETScCommTests:
    runs-on: ubuntu-latest 
   steps:
     - uses: actions/checkout@v2
     - uses: julia-actions/setup-julia@v1
       with:
         version: 1.6
         arch: x64 
     - uses: julia-actions/julia-buildpkg@latest
     - run: echo $PWD  
     - run: julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
     - run: cd test/MPIPETScTests/compile; ./compile.sh
     - run: julia --project=. --color=yes --check-bounds=yes test/MPIPETScTests/runtests.jl -i test/MPIPETScTests/compile/GridapDistributed.so  
